### PR TITLE
docs: update session commit

### PR DESCRIPTION
**Pull request by agatha197**
- Delete container commit and leave only session commit guide
- Add missing translation (KO) of preopen port guide
[연산 세션 — Backend.AI Web-UI User Guide 24.03 문서.pdf](https://github.com/user-attachments/files/15832020/Backend.AI.Web-UI.User.Guide.24.03.pdf)
[Compute Sessions — Backend.AI Web-UI User Guide 24.03 documentation.pdf](https://github.com/user-attachments/files/15832022/Compute.Sessions.Backend.AI.Web-UI.User.Guide.24.03.documentation.pdf)

### CODE REVIEW

**Review by lizable — APPROVED** [review]
LGTM.

**Comment by YEONFEEL96** [comment]
Seems like editing is not allowed in the most part. @agatha197 

이 다이얼로그에서 여러분은 사전 개방 포트를 추가하거나, 작성한 사전 개방 포트를 갱신하거나, 삭제할 수 있습니다. 더 자세히 알고 싶으실 경우 다이얼로그 헤더 부분에 있는 도움말 (?) 버튼을 클릭해주세요.
->
해당 다이얼로그에서 사전 개방 포트를 추가하거나, 작성한 사전 개방 포트를 갱신, 삭제할 수 있습니다. 더욱 자세한 설명이 필요한 경우, 다이얼로그 헤더 부분에 있는 도움말 (?) 버튼을 클릭해주세요.
---
사전 개방 포트는 컨테이너 내부 포트입니다. 따라서, 다른 앱들과 달리 세션 앱 런처에서 사전 개방 포트를 클릭하면 빈 페이지가 뜹니다. 
->
사전 개방 포트는 컨테이너 내부 포트입니다. 따라서, 다른 앱들과 달리 세션 앱 런처에서 사전 개방 포트를 클릭하면 빈 페이지가 나타납니다.
---
커밋 프로세스 중에 예기치 않은 오류를 방지하기 위해 세션을 종료할 수 없을 수 있습니다.
->
커밋 프로세스 중에 예기치 않은 오류를 방지하기 위해, 세션 종료를 명령하더라도 실제로는 종료되지 않을 수 있습니다.


**Seems like we need to change <Preopen> to <Pre-open or Pre-opened> but this needs to be cross-checked with developers.**

---
In the forth page of session creation page, you can add, update and delete written preopen ports.
->
In the forth page of session creation page, users can add, update and delete written preopen ports.
---
You can input between 1024  65535 port numbers to the input fields.
->
Users can put port numbers in between 1024 to 65535, to the input fields.
---
You can check the configured preopen ports in the session app launcher.
->
Users can check the configured preopen ports in the session app launcher.
---
The preopen ports are internal ports within the container. Therefore, unlike other apps, when you click on the preopen ports in the session app launcher, you will see a blank page. Please bind a server to the respective port before using it.
->
The preopen ports are the internal ports within the container. Therefore, unlike other apps, when users click the preopen ports in the session app launcher, a blank page will appear. Please bind a server to the respective port before use.
---
Currently, Backend.AI supports the “Convert Session to Image” feature only when the session is in INTERACTIVE mode. During the committing process, you may not be able to terminate the session to prevent unexpected errors. If you want to stop the ongoing process, please check the session and force-terminate the session.
->
Currently, Backend.AI supports “Convert Session to Image” only when the session is in INTERACTIVE mode. To prevent unexpected error, users may not be able to terminate the session during committing process. To stop the ongoing process, check the session, and force-terminate it.
---
The number of times you can Convert Session to Image may be limited by the user resource policy. In this case, try removing the existing customized image and retry, or contact the administrator.
->
The number of times to convert Session to image may be limited by the user resource policy. In this case, remove the existing customized image and try again. If this does not resolves the problem, please contact the administrator.

**Comment by agatha197** [comment]
> Seems like we need to change "Preopen" to "Pre-open or Pre-opened" but this needs to be cross-checked with developers.
@YEONFEEL96 We already discussed that, and decided to use "Preopen". It is also indicated as preopen in webui, so let's leave it as it is.

And thank you for the detailed feedback! I reflected them :)

**Review by YEONFEEL96 — APPROVED** [review]
LGTM

**Pull request merged**
