### PR TITLE
docs: use folder explorer and create a new folder in session launcher

### PR DESCRIPTION
**Pull request by ironAiken2**
### This PR is about updating `mounting folders to a compute session` section for 24.09

**Changes:**
- Added folder explorer functionality within session launcher 
- Added folder create functionality within session launcher. 
- Updated images for new components.

**Related PR:**
- https://github.com/lablup/backend.ai-webui/pull/2766 @yomybaby 
- https://github.com/lablup/backend.ai-webui/pull/2765 @yomybaby 
- https://github.com/lablup/backend.ai-webui/pull/2745 @ironAiken2 

PDF[ko] : [연산 세션에 폴더 마운트 — Backend.AI Web-UI User Guide 24.03 문서.pdf](https://github.com/user-attachments/files/17515723/Backend.AI.Web-UI.User.Guide.24.03.pdf)
PDF[en] : [Mounting Folders to a Compute Session — Backend.AI Web-UI User Guide 24.03 documentation.pdf](https://github.com/user-attachments/files/17515726/Mounting.Folders.to.a.Compute.Session.Backend.AI.Web-UI.User.Guide.24.03.documentation.pdf)

### CODE REVIEW

**Comment by ironAiken2** [comment]
* **#90** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-docs-webui/90?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by YEONFEEL96 — CHANGES_REQUESTED** [review]
Rebuild 'mount_vfolder' document to match latest UI and writing guideline.

**Review by YEONFEEL96 — CHANGES_REQUESTED** [review]
Rebuild 'mount_vfolder' document to match latest UI and writing guideline.

**Comment by ironAiken2** [comment]
> Rebuild 'mount_vfolder' document to match latest UI and writing guideline.

I've incorporated all the changes you've written. @YEONFEEL96

**Review by YEONFEEL96 — APPROVED** [review]
Thanks, Looks Good To Me.

**Comment by ironAiken2** [comment]
### Merge activity

* **Nov 22, 12:36 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/lablup/backend.ai-docs-webui/90).

**Pull request merged**
