### PR TITLE
docs: add my environments page and update commit session

### LINKED ISSUE #55: add docs: My Environment page
Let's add a new content about https://github.com/lablup/backend.ai-webui/pull/2332

### PR DESCRIPTION
**Pull request by agatha197**
resolves #55 
- Add My Environments page information.
- Add notes to session list page.
- Update version to 24.03
[Backend.AI WebUI User Guide 24.03.0(EN).pdf](https://github.com/lablup/backend.ai-docs-webui/files/15032341/Backend.AI.WebUI.User.Guide.24.03.0.EN.pdf)
[Backend.AI WebUI User Guide 24.03.0(KO).pdf](https://github.com/lablup/backend.ai-docs-webui/files/15032338/Backend.AI.WebUI.User.Guide.24.03.0.KO.pdf)

### CODE REVIEW

**Review by lizable — COMMENTED** [review]
I have one minor request. Except that, LGTM.

**Review by yomybaby — APPROVED** [review]
LGTM

**Comment by kimjmin** [comment]
LGTM

**Review by kimjmin — APPROVED** [review]
LGTM

**Review by lizable — COMMENTED** [review]
LGTM.

**Pull request merged**
